export const movies = [
    { id: 1, title: "The Dark Knight", genre: "Action" },
    { id: 2, title: "Inception", genre: "Sci-Fi" },
    { id: 3, title: "Gladiator", genre: "Action" },
    { id: 4, title: "Mad Max: Fury Road", genre: "Action" },
    { id: 5, title: "John Wick", genre: "Action" },
    { id: 6, title: "Die Hard", genre: "Action" },
    { id: 7, title: "The Matrix", genre: "Sci-Fi" },
    { id: 8, title: "Interstellar", genre: "Sci-Fi" },
    { id: 9, title: "Blade Runner 2049", genre: "Sci-Fi" },
    { id: 10, title: "Arrival", genre: "Sci-Fi" },

    { id: 11, title: "The Shawshank Redemption", genre: "Drama" },
    { id: 12, title: "Forrest Gump", genre: "Drama" },
    { id: 13, title: "Fight Club", genre: "Drama" },
    { id: 14, title: "The Godfather", genre: "Drama" },
    { id: 15, title: "The Green Mile", genre: "Drama" },
    { id: 16, title: "Parasite", genre: "Drama" },
    { id: 17, title: "Whiplash", genre: "Drama" },
    { id: 18, title: "Joker", genre: "Drama" },
    { id: 19, title: "There Will Be Blood", genre: "Drama" },
    { id: 20, title: "Moonlight", genre: "Drama" },

    { id: 21, title: "The Hangover", genre: "Comedy" },
    { id: 22, title: "Superbad", genre: "Comedy" },
    { id: 23, title: "Step Brothers", genre: "Comedy" },
    { id: 24, title: "Dumb and Dumber", genre: "Comedy" },
    { id: 25, title: "Groundhog Day", genre: "Comedy" },
    { id: 26, title: "The Big Lebowski", genre: "Comedy" },
    { id: 27, title: "Borat", genre: "Comedy" },
    { id: 28, title: "Jojo Rabbit", genre: "Comedy" },
    { id: 29, title: "Deadpool", genre: "Comedy" },
    { id: 30, title: "Tropic Thunder", genre: "Comedy" },

    { id: 31, title: "The Conjuring", genre: "Horror" },
    { id: 32, title: "Hereditary", genre: "Horror" },
    { id: 33, title: "It", genre: "Horror" },
    { id: 34, title: "A Nightmare on Elm Street", genre: "Horror" },
    { id: 35, title: "The Exorcist", genre: "Horror" },
    { id: 36, title: "Get Out", genre: "Horror" },
    { id: 37, title: "The Ring", genre: "Horror" },
    { id: 38, title: "Midsommar", genre: "Horror" },
    { id: 39, title: "Saw", genre: "Horror" },
    { id: 40, title: "The Witch", genre: "Horror" },

    { id: 41, title: "Titanic", genre: "Romance" },
    { id: 42, title: "The Notebook", genre: "Romance" },
    { id: 43, title: "La La Land", genre: "Romance" },
    { id: 44, title: "Pride & Prejudice", genre: "Romance" },
    { id: 45, title: "Before Sunrise", genre: "Romance" },
    { id: 46, title: "A Star Is Born", genre: "Romance" },
    { id: 47, title: "Her", genre: "Romance" },
    { id: 48, title: "Blue Valentine", genre: "Romance" },
    { id: 49, title: "Call Me by Your Name", genre: "Romance" },
    { id: 50, title: "The Fault in Our Stars", genre: "Romance" },

    { id: 51, title: "Se7en", genre: "Thriller" },
    { id: 52, title: "Gone Girl", genre: "Thriller" },
    { id: 53, title: "Prisoners", genre: "Thriller" },
    { id: 54, title: "Shutter Island", genre: "Thriller" },
    { id: 55, title: "Nightcrawler", genre: "Thriller" },
    { id: 56, title: "Zodiac", genre: "Thriller" },
    { id: 57, title: "No Country for Old Men", genre: "Thriller" },
    { id: 58, title: "The Silence of the Lambs", genre: "Thriller" },
    { id: 59, title: "Black Swan", genre: "Thriller" },
    { id: 60, title: "The Prestige", genre: "Thriller" },

    { id: 61, title: "The Lord of the Rings: Fellowship", genre: "Fantasy" },
    { id: 62, title: "The Lord of the Rings: Two Towers", genre: "Fantasy" },
    { id: 63, title: "The Lord of the Rings: Return of the King", genre: "Fantasy" },
    { id: 64, title: "Harry Potter and the Sorcerer's Stone", genre: "Fantasy" },
    { id: 65, title: "Harry Potter and the Chamber of Secrets", genre: "Fantasy" },
    { id: 66, title: "The Hobbit: An Unexpected Journey", genre: "Fantasy" },
    { id: 67, title: "Pan's Labyrinth", genre: "Fantasy" },
    { id: 68, title: "Avatar", genre: "Fantasy" },
    { id: 69, title: "Doctor Strange", genre: "Fantasy" },
    { id: 70, title: "The Chronicles of Narnia", genre: "Fantasy" }
];
